Update: error[E0603]: module  is private   --> core/crypto/src/ed25519.rs:44:16    | 44 | use rand_core::os::OsRng;    |                ^^ private module    | note: the module  is defined here   --> /home/freanzy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rand_core-0.6.4/src/lib.rs:56:31    | 56 | #[cfg(feature = getrandom)] mod os;    |                               ^^^^^^
error[E0603]: module  is private
  --> core/crypto/src/ed25519.rs:60:42
   |
60 |     pub fn generate(rng: &mut rand_core::os::OsRng) -> Self
   |                                          ^^ private module
   |
note: the module  is defined here
  --> /home/freanzy/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rand_core-0.6.4/src/lib.rs:56:31
   |
56 | #[cfg(feature = getrandom)] mod os;
   |                               ^^^^^^
help: consider importing one of these items instead
   |
60 |     pub fn generate(rng: &mut rand::rngs::OsRng) -> Self
   |                               ~~~~~~~~~~~~~~~~~
60 |     pub fn generate(rng: &mut rand_core::OsRng) -> Self
   |                               ~~~~~~~~~~~~~~~~

For more information about this error, try A private item was used outside its scope.

Erroneous code example:

```
mod foo {
    const PRIVATE: u32 = 0x_a_bad_1dea_u32; // This const is private, so we
                                            // can't use it outside of the
                                            // `foo` module.
}

println!("const value: {}", foo::PRIVATE); // error: constant `PRIVATE`
                                                  //        is private
```

In order to fix this error, you need to make the item public by using the `pub`
keyword. Example:

```
mod foo {
    pub const PRIVATE: u32 = 0x_a_bad_1dea_u32; // We set it public by using the
                                                // `pub` keyword.
}

println!("const value: {}", foo::PRIVATE); // ok!
```.
error: could not document